#!/usr/bin/env python
import sys
import re
import os.path

templates = ( ('module_header.template', 'src/{0}.h')
        , ('module_source.template', 'src/{0}.c')
        , ('module_test.template', 'tests/{0}_test.cpp'))

def process_template(template, output, name):
    source = open(template).read()
    source = source.replace('XX__XX', name.upper())
    source = source.replace('xx__xx', name)
    open(output, 'w').write(source)

def new_module(name):
    for tmplt, offmt in templates:
        of = offmt.format(name)
        if not os.path.exists(of):
            process_template(tmplt, of, name)

def usage():
    prg = os.path.basename(sys.argv[0])
    s = 'Usage: {0} <module name>\n'.format(prg)
    sys.stderr.write(s)

def main():
    try:
        name = sys.argv[1]
        new_module(name)
    except IndexError:
        usage()
        sys.exit(1)

if __name__ == '__main__':
    main()

